### ISSUE TITLE
求up一个xhs-api的包，感谢

### ISSUE THREAD

**Issue by hjhjhghghg** [gupingan/khs-pyside6#1]
我也写了一个全功能版的协议，但是基于playwright的，up的好像是js纯算的，效率应该更高
第一个star一下。
邮箱：412102438@qq.com

**Comment by gupingan** [comment]
> 我也写了一个全功能版的协议，但是基于playwright的，up的好像是js纯算的，效率应该更高 第一个star一下。 邮箱：[412102438@qq.com](mailto:412102438@qq.com)

已发送，请认真参阅邮件信息。

**Comment by hjhjhghghg** [comment]
> > 我也写了一个全功能版的协议，但是基于playwright的，up的好像是js纯算的，效率应该更高 第一个star一下。 邮箱：[412102438@qq.com](mailto:412102438@qq.com)
> 
> 已发送，请认真参阅邮件信息。

感谢up

**Comment by hjhjhghghg** [comment]
> > 我也写了一个全功能版的协议，但是基于playwright的，up的好像是js纯算的，效率应该更高 第一个star一下。 邮箱：[412102438@qq.com](mailto:412102438@qq.com)
> 
> 已发送，请认真参阅邮件信息。

大佬求个新的js，官方更新了

**Comment by gupingan** [comment]
> > > 我也写了一个全功能版的协议，但是基于playwright的，up的好像是js纯算的，效率应该更高 第一个star一下。 邮箱：[412102438@qq.com](mailto:412102438@qq.com)
> > 
> > 
> > 已发送，请认真参阅邮件信息。
> 
> 大佬求个新的js，官方更新了

已发送

**Comment by gupingan** [comment]
[关于 Donate](https://github.com/gupingan/khs-pyside6/issues/20)
