### ISSUE TITLE
求个api包，感谢 大佬开源

### ISSUE THREAD

**Issue by kk130398** [gupingan/khs-pyside6#10]
1303984619@qq.com

**Comment by gupingan** [comment]
不好意思老兄，新版的xhsapi不打算开源了，老是有人二卖有点烦，8月8号已经逆向，最近发现 x-s-common 的计算速度比较慢，正在做优化，后续也可能开启打赏，我这边至少比那些 csdn 闲鱼上的卖家便宜一半，后续我开放打赏通道再统一给大家发吧
