### ISSUE TITLE
大佬求个 xhs-api 包  18625787756@163.com

### ISSUE THREAD

**Issue by liguang3** [gupingan/khs-pyside6#11]

**Comment by oOyH** [comment]
大佬求个api包，感谢大佬开源tuyun4912@gmail.com

**Comment by gupingan** [comment]
不好意思啊各位，新版的xhsapi不打算开源了，老是有人二卖有点烦了，8月8号已经逆向完了，只是最近给客户弄采集发现 x-s-common 的计算速度比较慢，正在做优化，后续也可能开启打赏，我这边至少比那些 csdn 闲鱼上的卖家便宜一半，后续我开放打赏通道再统一给大家发吧

**Comment by gupingan** [comment]
[关于 Donate](https://github.com/gupingan/khs-pyside6/issues/20)
