### ISSUE TITLE
1181580150@qq.com 感谢

### ISSUE THREAD

**Issue by lizhixiang0** [gupingan/khs-pyside6#12]

**Comment by gupingan** [comment]
额，不好意思哈，新版的xhsapi不打算开源了，老是有人二卖有点烦，最近发现 x-s-common 的计算速度比较慢，正在做优化，后续也可能开启打赏机制，我这边至少比那些 csdn 闲鱼上的卖家便宜一半，后续我开放打赏通道再统一给大家发吧

**Comment by gupingan** [comment]
[关于 Donate](https://github.com/gupingan/khs-pyside6/issues/20)
