### ISSUE TITLE
求api包 已stars!

### ISSUE THREAD

**Issue by PrintX05** [gupingan/khs-pyside6#16]
3042627767@qq.com

**Comment by gupingan** [comment]
额，不好意思，新版的xhsapi不打算开源了，老是有人二卖有点烦，8月8号已经逆向，但是最近发现 x-s-common 的计算速度比较慢，正在做优化，后续也可能开启打赏机制，我这边至少比那些 csdn 闲鱼上的卖家便宜一半，后续我开放打赏通道再统一给大家发吧

**Comment by PrintX05** [comment]
好吧😭😭😭



---原始邮件---
发件人: "顾平安(Gu ***@***.***&gt;
发送时间: 2024年8月12日(周一) 凌晨1:13
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [gupingan/khs-pyside6] 求api包 已stars! (Issue #16)




 
额，不好意思，新版的xhsapi不打算开源了，老是有人二卖有点烦，8月8号已经逆向，但是最近发现 x-s-common 的计算速度比较慢，正在做优化，后续也可能开启打赏机制，我这边至少比那些 csdn 闲鱼上的卖家便宜一半，后续我开放打赏通道再统一给大家发吧

**Comment by gupingan** [comment]
[关于 Donate](https://github.com/gupingan/khs-pyside6/issues/20)
