### ISSUE TITLE
求 API , 已给星，也想加入维护

### ISSUE THREAD

**Issue by monochrome-yeh** [gupingan/khs-pyside6#19]
已给星
也想加入contributor

如还有余地给api的话，也麻烦求一个
dlikeayu2+github@gmail.com
需要以专案维护方式可以另行讨论喔！

有donate 的渠道可以和我说

**Comment by gupingan** [comment]
[关于 Donate](https://github.com/gupingan/khs-pyside6/issues/20)

**Comment by monochrome-yeh** [comment]
说到做到！有机会一起合作！
