### ISSUE TITLE
先留下邮箱慢慢学习吧

### ISSUE THREAD

**Issue by Lawrence666** [gupingan/khs-pyside6#2]
981427857@qq.com

**Comment by gupingan** [comment]
已发送 xhs-api 包

**Comment by Garfield-Kwok** [comment]
1026841353@qq.com,  初学者， 想跟着您的代码慢慢学习，谢谢

**Comment by gupingan** [comment]
> [1026841353@qq.com](mailto:1026841353@qq.com), 初学者， 想跟着您的代码慢慢学习，谢谢

已发送

**Comment by LiLiaoBin** [comment]
期待xhs-api 包，学习学习，谢谢！

xx@xxmubiao.com

**Comment by gupingan** [comment]
> 期待xhs-api 包，学习学习，谢谢！
> 
> [xx@xxmubiao.com](mailto:xx@xxmubiao.com)

已发送

**Comment by gupingan** [comment]
> [981427857@qq.com](mailto:981427857@qq.com)

官方更新了 js 加密，需要请回复（使用方式：直接替换包中 的 xhs-api.js 文件）

**Comment by gupingan** [comment]
> [1026841353@qq.com](mailto:1026841353@qq.com), 初学者， 想跟着您的代码慢慢学习，谢谢

官方更新了 js 加密，需要请回复（使用方式：直接替换包中 的 xhs-api.js 文件）

**Comment by gupingan** [comment]
> 期待xhs-api 包，学习学习，谢谢！
> 
> [xx@xxmubiao.com](mailto:xx@xxmubiao.com)

官方更新了 js 加密，需要请回复（使用方式：直接替换包中 的 xhs-api.js 文件）

**Comment by LiLiaoBin** [comment]
> > 期待xhs-api 包，学习学习，谢谢！
> > [xx@xxmubiao.com](mailto:xx@xxmubiao.com)
> 
> 官方更新了 js 加密，需要请回复（使用方式：直接替换包中 的 xhs-api.js 文件）

xhs-api 包已经收到，感谢！再次期待更新后的 xhs-api.js 文件

**Comment by gupingan** [comment]
> > > 期待xhs-api 包，学习学习，谢谢！
> > > [xx@xxmubiao.com](mailto:xx@xxmubiao.com)
> > 
> > 
> > 官方更新了 js 加密，需要请回复（使用方式：直接替换包中 的 xhs-api.js 文件）
> 
> xhs-api 包已经收到，感谢！再次期待更新后的 xhs-api.js 文件

已发送

**Comment by Garfield-Kwok** [comment]
> > [1026841353@qq.com](mailto:1026841353@qq.com), 初学者， 想跟着您的代码慢慢学习，谢谢
> 
> 官方更新了 js 加密，需要请回复

需要，感谢您

**Comment by hardywu** [comment]
ripicaco@duck.com python学习 。求顾佬发包。  @gupingan

**Comment by gupingan** [comment]
> [ripicaco@duck.com](mailto:ripicaco@duck.com) python学习 。求顾佬发包。 @gupingan

你的邮箱满了吗？可能我今天发送多了，暂时没法发邮件了

![截图_20240731193328](https://github.com/user-attachments/assets/5f062990-b7e9-4f0f-be76-de30ab3c6371)

**Comment by hardywu** [comment]
@gupingan  换这个试试 v4u2qv2mc@mozmail.com

**Comment by gupingan** [comment]
> v4u2qv2mc@mozmail.com

已发送

**Comment by hardywu** [comment]
@gupingan 大佬，mozmail好像不收10mb以上的邮件。。麻烦再试试 kqnuossf@protonmail.com， 可以收25mb

**Comment by gupingan** [comment]
[关于 Donate](https://github.com/gupingan/khs-pyside6/issues/20)
