### ISSUE TITLE
您好，请问是否可以部署到服务端

### ISSUE THREAD

**Issue by C-L-STARK** [gupingan/khs-pyside6#21]
您好，请问是否可以部署到服务端；

您好，我们需要长期做一个爬虫定向爬取。请问是否支持该操作；
例如我们把cookie塞进去，您这边的接口负责执行网络请求并返回就行。

如果可行的话，我们立刻加入您的仓库，期待您的回复谢谢。

另外可否回复下功能包具体的API接口内容以及能力。

**Comment by gupingan** [comment]
本包并非服务端，支持集成在服务端，Java 等非 Python 后端框架需要自行查看一下跨语言调用的问题，Python 后端（Flask、Django 等）可直接环境下安装包后调用。
高并发情况推荐打赏 x-xhs 的项目。
涵盖 xhs web 端90%+接口（登录、笔记、评论、表情包、举报等方面各种操作的接口）

**Comment by gupingan** [comment]
> 您好，请问是否可以部署到服务端；
> 
> 您好，我们需要长期做一个爬虫定向爬取。请问是否支持该操作； 例如我们把cookie塞进去，您这边的接口负责执行网络请求并返回就行。
> 
> 如果可行的话，我们立刻加入您的仓库，期待您的回复谢谢。
> 
> 另外可否回复下功能包具体的API接口内容以及能力。

打赏规则参见：https://github.com/gupingan/khs-pyside6/issues/20

**Comment by TONY-STARK-TECH** [comment]
嗯，打赏规则已经清楚。

请问 Cookie 在高并发情况下，是否会出现封号情况呢？是否需要使用静态代理？

**Comment by gupingan** [comment]
> 嗯，打赏规则已经清楚。
> 
> 请问 Cookie 在高并发情况下，是否会出现封号情况呢？是否需要使用静态代理？

得看你干的啥了，太频繁肯定不行的，可以不用代理啥的（至少我这边写采集软件是用不到的），而且现在官方有反爬，同一账号与不同的笔记下的内容并发交互的情况接口会提示访问频繁
