### ISSUE TITLE
是否可以进行评论 的点赞

### ISSUE THREAD

**Issue by 717315051** [gupingan/khs-pyside6#22]
如题的功能是否能完成

**Comment by gupingan** [comment]
可以，web 端能有的，包上都有的哈

**Comment by 717315051** [comment]
可以加微信要展示图吗 我想购买开原版  zjdgdcb

**Comment by 717315051** [comment]
我是一个在校高三学生 我想购买开源版进行学习  我有证明可以证明我是一个高中生

**Comment by gupingan** [comment]
> 我是一个在校高三学生 我想购买开源版进行学习 我有证明可以证明我是一个高中生

当前这个软件不能对评论进行点赞，底层是调用 xhs 包，当前软件的代码已经呈现在仓库中，如果你需要 xhs 包，你首先需要 Python基础，其次这个包已经不在免费，你还是学生我可以给你优惠 20 元。最后建议你还是先看看赞助档位，你应该是想要代码学习是吗？看看赞助标准和对应我能给你的东西

**Comment by gupingan** [comment]
> 我是一个在校高三学生 我想购买开源版进行学习 我有证明可以证明我是一个高中生

xhs 包 包含了几乎百分之九十九红薯官网的接口，当前这个软件已经很旧了，他没有点赞评论的功能，不过 xhs 包 可以点赞评论。

**Comment by 717315051** [comment]
能否加我微信 zjdgdcb
