### ISSUE TITLE
学习一下，求个api

### ISSUE THREAD

**Issue by qianlongzju** [gupingan/khs-pyside6#3]
邮箱 406645820@qq.com
感谢大佬， 碰到问题会反馈给大佬

**Comment by gupingan** [comment]
已发送

**Comment by gupingan** [comment]
官方更新了 js 加密，需要请回复（使用方式：直接替换包中 的 xhs-api.js 文件）

**Comment by Heyastroom** [comment]
2737305237@qq.com可以求一个嘛？
PS:现在API都加密，怎么找到对应方法的....

**Comment by gupingan** [comment]
> [2737305237@qq.com](mailto:2737305237@qq.com)可以求一个嘛？ PS:现在API都加密，怎么找到对应方法的....

已发送，查看使用说明就行，一个方法直接引入新的 xhs-api.js 即可。
