### ISSUE TITLE
运行前是不是要启动virtual env什么的？

### ISSUE THREAD

**Issue by qianlongzju** [gupingan/khs-pyside6#4]
一直缺少python库，已经按步骤安装了

![image](https://github.com/user-attachments/assets/99c1cdca-8cc0-4a3c-a47f-1f34beda281e)

**Comment by gupingan** [comment]
> 一直缺少python库，已经按步骤安装了
> 
> ![image](https://private-user-images.githubusercontent.com/769655/350681979-99c1cdca-8cc0-4a3c-a47f-1f34beda281e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE0NzA4MjcsIm5iZiI6MTcyMTQ3MDUyNywicGF0aCI6Ii83Njk2NTUvMzUwNjgxOTc5LTk5YzFjZGNhLThjYzAtNGEzYy1hNDdmLTFmMzRiZWRhMjgxZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyMFQxMDE1MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYzI2YzFlMTcwY2I5NGRlZmNmNzZjMGM2NDA2ZTY1YjI4MjM1ZmEzZmU2ZTg1NTMxZTQ4YjUxN2U5N2VlNTI4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.aNbTUZHGafOsbGZWD9zoX5RT7bld1nTXlJrp3kGyt4U)

使用了 `poetry install` 后，说明 poetry 开辟出来的这个环境中，相关依赖都已经安装了，但是我看你好像是在终端中启动 `main.py` 文件，那么可能你的启动方式是有点问题的，你可以运行下方的命令启动：

```bash
poetry run python main.py
```

该命令意思是 在当前所在目录对应的虚拟环境中，通过 python 运行 main.py，这样就能读取到相关依赖了

**Comment by qianlongzju** [comment]
嗯，启动了。软件的使用逻辑不是很明白

**Comment by gupingan** [comment]
> 嗯，启动了。软件的使用逻辑不是很明白

账号管理添加账号，配置管理添加配置，创建单元（选择1份配置 + 若干账号）执行任务即可运行

**Comment by qianlongzju** [comment]
感谢

**Comment by gupingan** [comment]
[关于 Donate](https://github.com/gupingan/khs-pyside6/issues/20)
