### ISSUE TITLE
大佬求发 感谢感谢

### ISSUE THREAD

**Issue by zachary-1226** [gupingan/khs-pyside6#5]

**Comment by ZillionaireL** [comment]
zhoule0306@outlook.com 辛苦感谢感谢

**Comment by gupingan** [comment]
> [zhoule0306@outlook.com](mailto:zhoule0306@outlook.com) 辛苦感谢感谢

已发送

**Comment by ZillionaireL** [comment]
谢谢～
发自我的 iPhone

在 2024年7月24日，下午6:45，顾平安(Gu Pingan) ***@***.***> 写道：

﻿

***@***.******@***.***> 辛苦感谢感谢

已发送

**Comment by gupingan** [comment]
[关于 Donate](https://github.com/gupingan/khs-pyside6/issues/20)
