### ISSUE TITLE
求api包感谢大佬开源

### ISSUE THREAD

**Issue by han610** [gupingan/khs-pyside6#8]
363612416@qq.com

**Comment by gupingan** [comment]
> 363612416@qq.com

已发送

**Comment by Ustinian1722** [comment]
1722883727@qq.com
求api包

**Comment by gupingan** [comment]
> [1722883727@qq.com](mailto:1722883727@qq.com) 求api包

已发送

**Comment by fredalao** [comment]
segafans_ljx@163.com
求api包

**Comment by gupingan** [comment]
> [segafans_ljx@163.com](mailto:segafans_ljx@163.com) 求api包

已发送

**Comment by poer2023** [comment]
whattyy@163.com 求api包谢谢

**Comment by Mrack** [comment]
[840870819@qq.com](mailto:840870819@qq.com) 求api包谢谢

**Comment by gupingan** [comment]
> [whattyy@163.com](mailto:whattyy@163.com) 求api包谢谢

已发送

**Comment by gupingan** [comment]
> [840870819@qq.com](mailto:840870819@qq.com) 求api包谢谢

已发送
